[project]
name = "snc-sf"
version = "1.1.0"
description = ""
authors = [
    {name = "imedan",email = "ilija.medan@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "astropy (>=6.1.0)",
    "numpy (>=2.0.0)",
    "matplotlib (>=3.8.0)",
    "healpy (>=1.17.1)",
    "tqdm (>=4.60.0)",
    "sdss-semaphore (>=0.2.4,<0.3.0)",
    "gaiaunlimited (>=0.3.2,<0.4.0)",
    "polars (>=1.0.0)",
    "jax (>=0.4.27,<0.9.0)",
    "jaxlib (>=0.4.27,<0.9.0)",
    "notebook (>=7.0.0)",
    "jaxopt (>=0.8.5,<0.9.0)",
    "numpyro (>=0.14.0,<0.21.0)",
    "pyarrow (>=14.0.0)",
    "astroquery (>=0.4.7)",
    "scipy (>=1.13.0)",
]

[tool.poetry]
packages = [{include = "snc_sf", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pytest = ">=8.0.0"
