[project]
name = "snc-sf"
version = "0.1.0"
description = ""
authors = [
    {name = "imedan",email = "ilija.medan@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "astropy (>=6.0.1,<7.0.0)",
    "numpy (>=2.2.4,<3.0.0)",
    "matplotlib (>=3.10.1,<4.0.0)",
    "healpy (>=1.18.1,<2.0.0)",
    "polars-lts-cpu (>=1.27.1,<2.0.0)",
    "tqdm (>=4.67.1,<5.0.0)",
]

[tool.poetry]
packages = [{include = "snc_sf", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
